package com.example.dshinde.myapplication_xmlpref.common;

public class Constants {
    public static final String TEXT_PLAIN = "text/plain";
    public static final String TEXT_HTML = "text/html";
    public static final String KEY = "key";
    public static final String VALUE = "value";
    public static final String STORAGE_PATH_NOTES = "MyNotes/";
    public static final String DATABASE_PATH_NOTES = "MyNotes";
    public static final String DATABASE_PATH_NOTE_DETAILS = "NoteDetails";
    public static final String CR_LF = "\n";
    public static final String CAFE_SETTINGS = "CafeSettings";
    public static final String SHABDA_KOSH = "ShabdaKosh";
    public static final int REQUEST_CODE_SCREEN_DESIGN = 501;
    public static final int REQUEST_CODE_SCREEN_PREVIEW = 502;
    public static final int REQUEST_CODE_SCREEN_CAPTURE = 503;
    public static final int RESULT_CODE_OK = 1;
    public static final int RESULT_CODE_CANCEL = -1;
    public static final String SCREEN_DESIGN_NOTE_PREFIX = "screenDesign:";
    public static final String MEDIA_NOTE_PREFIX = "mediaNote:";
    public static final int DRAWABLE_LEFT = 0;
    public static final int DRAWABLE_TOP = 1;
    public static final int DRAWABLE_RIGHT = 2;
    public static final int DRAWABLE_BOTTOM = 3;
    public static final int TAKE_PHOTO=504;
    public static final int SELECT_IMAGE =505;
    public static final int SELECT_DOCUMENT =506;
    public static final int SELECT_MYNOTE =507;
    public static final int SELECT_AUDIO =508;
    public static final String[] EMPTY_ARRAY={};
    public static final String IMAGE_FILE="image/*";
    public static final String PDF_FILE="application/pdf";
    public static final String AUDIO_FILE="audio/*";
    public static final String VIEW_NOTE = "View Note";
    public static final String PLAY_NOTE = "Play Audio Note";
    public static final String NAAMASMRAN = "Naamasmran";
    public static final String AUDIO_NOTE = "Audio Note";
    public static final String SCREEN_DESIGN = "Screen Design";
    public static final String VIEW_RELATIONSHIP = "Relationship";
}
